In [0]:
import torch

In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1,5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [5]:
print(features)
print(weights)
#weights=weights.reshape(5,1)
print(weights.shape)
print(weights)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
torch.Size([1, 5])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])


In [6]:
y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.1595]])


In [7]:
y = activation(torch.mm(features, weights.reshape(5,1)) + bias)
print(y)

tensor([[0.1595]])


In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [9]:
h=activation(torch.mm(features,W1)+B1)
output =activation(torch.mm(h,W2)+B2)
print(output)

tensor([[0.3171]])


# **Numpy to Torch and back**

Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use torch.from_numpy(). To convert a tensor to a Numpy array, use the .numpy() method.

In [10]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.76440368, 0.42433382, 0.27756191],
       [0.96327681, 0.72479534, 0.18498703],
       [0.79062503, 0.76827064, 0.46930612],
       [0.79923771, 0.61923793, 0.51773576]])

In [11]:
b=torch.from_numpy(a) ## convert numpy to tensor
b

tensor([[0.7644, 0.4243, 0.2776],
        [0.9633, 0.7248, 0.1850],
        [0.7906, 0.7683, 0.4693],
        [0.7992, 0.6192, 0.5177]], dtype=torch.float64)

In [12]:
b.numpy() # convert tensor to numpy

array([[0.76440368, 0.42433382, 0.27756191],
       [0.96327681, 0.72479534, 0.18498703],
       [0.79062503, 0.76827064, 0.46930612],
       [0.79923771, 0.61923793, 0.51773576]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [13]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.5288, 0.8487, 0.5551],
        [1.9266, 1.4496, 0.3700],
        [1.5813, 1.5365, 0.9386],
        [1.5985, 1.2385, 1.0355]], dtype=torch.float64)

In [14]:
# Numpy array matches new values from Tensor
a

array([[1.52880737, 0.84866764, 0.55512381],
       [1.92655361, 1.44959068, 0.36997407],
       [1.58125006, 1.53654128, 0.93861224],
       [1.59847541, 1.23847587, 1.03547151]])